name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | while read file; do

            case "${file,,}" in
              *.html)
                ICON="<:html:1534602268207480893>"
                ;;
              *.css)
                ICON="<:css:1534602328362057860>"
                ;;
              *.js)
                ICON="<:js:1534602388277825698>"
                ;;
              *.json)
                ICON="<:json:1534602817761972365>"
                ;;
              *.cpp|*.cc|*.h)
                ICON="<:cpp:1534605048850415757>"
                ;;
              *.py)
                ICON="<:py:1534604486046253127>"
                ;;
              *.png|*.jpg|*.jpeg|*.gif|*.webp|*.svg)
                ICON="<:img:1536685954247565342>"
                ;;
              *.mp3|*.wav|*.ogg|*.flac|*.m4a)
                ICON="<:audio:1536686006181306379>"
                ;;
              *.txt|*.md)
                ICON="<:txt:1536686079288021103>"
                ;;
              *)
                ICON="<:file:1534603227453063168>"
                ;;
            esac

            echo "- $ICON [$file](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/$file)"

          done)

          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Discord message
        run: |
          MESSAGE=$(cat <<EOF
          || <@&1534146629555327027> ||

          🚀 Új frissítés érkezett a GitHub repóba!

          📦 Repository: ${{ github.repository }}
          👤 Készítette: ${{ github.actor }}

          📝 Commit: [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})

          🔗 Weblap: [f0x3y.github.io](https://f0x3y.github.io)

          <:folder:1536686130164932638> Módosított fájlok:
          ${{ steps.changed.outputs.files }}
          EOF
          )

          jq -n \
            --arg content "$MESSAGE" \
            '{
              content: $content,
              flags: 4
            }' \
          | curl \
            -H "Content-Type: application/json" \
            -X POST \
            -d @- \
            ${{ secrets.DISCORD_WEBHOOK }}